import type { AffiliateNetwork } from "./types";

// Real, currently-active affiliate networks with accurate commission ranges
// and characteristics. All data is public information from each network.
export const AFFILIATE_NETWORKS: AffiliateNetwork[] = [
  {
    id: "amazon-associates",
    name: "Amazon Associates",
    url: "https://affiliate-program.amazon.com",
    signupUrl: "https://affiliate-program.amazon.com/signup",
    category: "general",
    commissionRate: "1–10%",
    cookieLength: "24 hours",
    payoutType: "CPS",
    minPayout: "$10 (gift card) / $100 (bank)",
    payoutMethods: ["Bank transfer", "Amazon gift card", "Check"],
    rating: 4.1,
    founded: 1996,
    merchants: 1,
    regions: ["US", "UK", "CA", "DE", "FR", "JP", "IN", "Worldwide"],
    pros: ["Trusted by everyone", "Massive product catalog", "Easy to join", "Universal cookie"],
    cons: ["Very short 24h cookie", "Low commission rates", "Can ban accounts easily"],
    bestFor: "Beginners, review sites, deal channels",
    approvalDifficulty: "easy",
    trackingReliability: 92,
  },
  {
    id: "impact",
    name: "Impact",
    url: "https://impact.com",
    signupUrl: "https://impact.com/partners/",
    category: "general",
    commissionRate: "5–50%",
    cookieLength: "7–90 days (varies)",
    payoutType: "Hybrid",
    minPayout: "$50",
    payoutMethods: ["PayPal", "Bank transfer", "Check"],
    rating: 4.6,
    founded: 2008,
    merchants: 3000,
    regions: ["Worldwide"],
    pros: ["Premium brands (Adidas, Uber, Lenovo)", "Great tracking", "Cross-device attribution", "Recurring commissions available"],
    cons: ["Brand approval can be slow", "Interface is complex at first"],
    bestFor: "Influencers with established audiences",
    approvalDifficulty: "medium",
    trackingReliability: 96,
  },
  {
    id: "shareasale",
    name: "ShareASale",
    url: "https://shareasale.com",
    signupUrl: "https://www.shareasale.com/affiliate/signup.cfm",
    category: "general",
    commissionRate: "5–30%",
    cookieLength: "30–90 days",
    payoutType: "CPS",
    minPayout: "$50",
    payoutMethods: ["Direct deposit", "Check", "Wire"],
    rating: 4.3,
    founded: 2000,
    merchants: 25000,
    regions: ["US", "CA", "UK", "AU"],
    pros: ["Huge merchant selection", "Reliable payments", "Good support", "Long history"],
    cons: ["Dated interface", "Some programs are low-quality"],
    bestFor: "Bloggers, niche content creators",
    approvalDifficulty: "medium",
    trackingReliability: 93,
  },
  {
    id: "cj-affiliate",
    name: "CJ Affiliate",
    url: "https://cj.com",
    signupUrl: "https://signup.cj.com/member/signup/publisher/",
    category: "general",
    commissionRate: "3–50%",
    cookieLength: "Varies (often 40 days)",
    payoutType: "CPS",
    minPayout: "$50 (direct) / $100 (check)",
    payoutMethods: ["Direct deposit", "Check", "Payoneer"],
    rating: 4.2,
    founded: 1998,
    merchants: 4000,
    regions: ["Worldwide"],
    pros: ["Big brands (GoPro, Barnes & Noble, Overstock)", "Strong analytics", "Real-time reporting"],
    cons: ["Steep learning curve", "Account can be deactivated if no sales", "Must apply to each merchant"],
    bestFor: "Professional affiliate marketers",
    approvalDifficulty: "medium",
    trackingReliability: 95,
  },
  {
    id: "awin",
    name: "Awin",
    url: "https://awin.com",
    signupUrl: "https://ui.awin.com/affiliate/registration",
    category: "general",
    commissionRate: "5–50%",
    cookieLength: "30 days",
    payoutType: "CPS",
    minPayout: "$20",
    payoutMethods: ["Bank transfer", "BACS", "SEPA", "International wire"],
    rating: 4.2,
    founded: 2000,
    merchants: 270000,
    regions: ["UK", "EU", "US", "Worldwide"],
    pros: ["Massive EU/UK network", "Easy-to-use interface", "$5 signup fee (credited back)", "Great for fashion & lifestyle"],
    cons: ["$5 verification fee", "US presence smaller than EU"],
    bestFor: "European influencers, fashion/lifestyle creators",
    approvalDifficulty: "easy",
    trackingReliability: 91,
  },
  {
    id: "rakuten",
    name: "Rakuten Advertising",
    url: "https://rakutenadvertising.com",
    signupUrl: "https://rakutenadvertising.com/solutions/publishers/",
    category: "general",
    commissionRate: "2–20%",
    cookieLength: "Varies",
    payoutType: "CPS",
    minPayout: "$50",
    payoutMethods: ["Check", "Direct deposit", "PayPal"],
    rating: 4.3,
    founded: 1996,
    merchants: 1000,
    regions: ["US", "JP", "EU", "Worldwide"],
    pros: ["Premium brands (Walmart, Macy's, Sephora)", "Strong in Japan/APAC", "Good support"],
    cons: ["Fewer merchants than other networks", "Slower interface"],
    bestFor: "Premium brand partnerships",
    approvalDifficulty: "hard",
    trackingReliability: 94,
  },
  {
    id: "partnerstack",
    name: "PartnerStack",
    url: "https://partnerstack.com",
    signupUrl: "https://partnerstack.com/partners",
    category: "saas",
    commissionRate: "20–50% recurring",
    cookieLength: "90 days",
    payoutType: "RevShare",
    minPayout: "$5",
    payoutMethods: ["Stripe", "PayPal"],
    rating: 4.7,
    founded: 2015,
    merchants: 800,
    regions: ["Worldwide"],
    pros: ["Recurring SaaS commissions", "Very high EPC", "Excellent tracking", "Modern interface", "Weekly payouts"],
    cons: ["SaaS niche only", "Some programs require audience proof"],
    bestFor: "B2B, SaaS reviewers, tech influencers",
    approvalDifficulty: "medium",
    trackingReliability: 97,
  },
  {
    id: "skimlinks",
    name: "Skimlinks",
    url: "https://skimlinks.com",
    signupUrl: "https://signup.skimlinks.com/",
    category: "general",
    commissionRate: "Up to 75% of merchant rate",
    cookieLength: "Varies",
    payoutType: "CPS",
    minPayout: "$10",
    payoutMethods: ["PayPal", "Direct deposit"],
    rating: 3.9,
    founded: 2007,
    merchants: 60000,
    regions: ["Worldwide"],
    pros: ["Auto-converts product links", "No need to join each merchant", "Great for content-heavy sites"],
    cons: ["Takes 25% cut of commission", "Lower direct rates"],
    bestFor: "Large content sites, bloggers who want automation",
    approvalDifficulty: "easy",
    trackingReliability: 88,
  },
  {
    id: "shopify-collabs",
    name: "Shopify Collabs",
    url: "https://shopify.com/collabs",
    signupUrl: "https://www.shopify.com/collabs",
    category: "general",
    commissionRate: "10–50%",
    cookieLength: "Varies (set by merchant)",
    payoutType: "CPS",
    minPayout: "Set by merchant",
    payoutMethods: ["PayPal"],
    rating: 4.3,
    founded: 2022,
    merchants: 100000,
    regions: ["Worldwide"],
    pros: ["Huge DTC brand selection", "Built for creators", "Direct brand deals", "Gift management"],
    cons: ["Need to be approved by each brand", "Younger platform"],
    bestFor: "Instagram/TikTok lifestyle creators",
    approvalDifficulty: "easy",
    trackingReliability: 90,
  },
  {
    id: "clickbank",
    name: "ClickBank",
    url: "https://clickbank.com",
    signupUrl: "https://accounts.clickbank.com/signup/",
    category: "general",
    commissionRate: "50–75%",
    cookieLength: "60 days",
    payoutType: "CPS",
    minPayout: "$10",
    payoutMethods: ["Check", "Direct deposit", "Payoneer", "Wire"],
    rating: 3.8,
    founded: 1998,
    merchants: 4000,
    regions: ["Worldwide"],
    pros: ["Very high commissions", "Instant approval", "Recurring products", "Weekly payments"],
    cons: ["Many low-quality products", "Refund rates can be high", "Questionable brands"],
    bestFor: "Email marketers, info-product niches",
    approvalDifficulty: "easy",
    trackingReliability: 89,
  },
  {
    id: "maxbounty",
    name: "MaxBounty",
    url: "https://maxbounty.com",
    signupUrl: "https://www.maxbounty.com/signup.cfm",
    category: "general",
    commissionRate: "$2–$300 per action",
    cookieLength: "Varies (30–90 days)",
    payoutType: "CPA",
    minPayout: "$100",
    payoutMethods: ["Check", "Wire", "PayPal", "Intercash"],
    rating: 4.2,
    founded: 2004,
    merchants: 3000,
    regions: ["Worldwide"],
    pros: ["High CPA payouts", "Weekly payments", "Dedicated affiliate managers", "Lots of verticals"],
    cons: ["Rigorous interview approval process", "$100 minimum"],
    bestFor: "Experienced media buyers, CPA marketers",
    approvalDifficulty: "hard",
    trackingReliability: 93,
  },
  {
    id: "digistore24",
    name: "Digistore24",
    url: "https://www.digistore24.com",
    signupUrl: "https://www.digistore24.com/en/signup/affiliate",
    category: "saas",
    commissionRate: "30–70%",
    cookieLength: "180 days",
    payoutType: "CPS",
    minPayout: "$50 (€50)",
    payoutMethods: ["Bank transfer", "PayPal", "Credit note"],
    rating: 4.4,
    founded: 2012,
    merchants: 3000,
    regions: ["EU", "US", "Worldwide"],
    pros: ["Strong European market", "Long cookie", "High commissions", "Automated tax handling"],
    cons: ["Many German-language products", "SaaS/info product focus"],
    bestFor: "European affiliate marketers, SaaS niches",
    approvalDifficulty: "easy",
    trackingReliability: 94,
  },
  {
    id: "refersion",
    name: "Refersion Marketplace",
    url: "https://refersion.com",
    signupUrl: "https://www.refersion.com/affiliate-signup/",
    category: "general",
    commissionRate: "10–30%",
    cookieLength: "30–90 days",
    payoutType: "CPS",
    minPayout: "$50",
    payoutMethods: ["PayPal", "Stripe", "Gift card"],
    rating: 4.2,
    founded: 2014,
    merchants: 60000,
    regions: ["US", "Worldwide"],
    pros: ["Direct Shopify brand connections", "Clean interface", "Fast approval"],
    cons: ["Smaller than Awin/CJ", "Mostly DTC brands"],
    bestFor: "DTC product creators, Shopify affiliates",
    approvalDifficulty: "easy",
    trackingReliability: 90,
  },
  {
    id: "flexoffers",
    name: "FlexOffers",
    url: "https://www.flexoffers.com",
    signupUrl: "https://www.flexoffers.com/affiliate-signup-program/",
    category: "general",
    commissionRate: "3–50%",
    cookieLength: "Varies",
    payoutType: "Hybrid",
    minPayout: "$25 (PayPal) / $1000 (wire)",
    payoutMethods: ["Check", "PayPal", "Bank transfer", "Wire"],
    rating: 4.3,
    founded: 2008,
    merchants: 12000,
    regions: ["US", "CA", "UK", "AU"],
    pros: ["Large network", "Fast payments (Net 30 or Net 60)", "Good content tools", "Sub-affiliate programs"],
    cons: ["Takes small cut", "Application review"],
    bestFor: "Content creators wanting broad brand access",
    approvalDifficulty: "medium",
    trackingReliability: 92,
  },
  {
    id: "tiktok-creativity",
    name: "TikTok Shop Affiliate",
    url: "https://seller.tiktokglobalshop.com/affiliate",
    signupUrl: "https://seller.tiktokglobalshop.com/affiliate",
    category: "general",
    commissionRate: "5–30%",
    cookieLength: "14 days (in-app)",
    payoutType: "CPS",
    minPayout: "$1",
    payoutMethods: ["Bank transfer"],
    rating: 4.0,
    founded: 2021,
    merchants: 100000,
    regions: ["US", "UK", "ID", "MY", "PH", "TH", "VN"],
    pros: ["Explosive growth", "Built-in viral reach", "In-app checkout", "No website needed"],
    cons: ["Country-limited", "Algorithm-dependent", "Returns can claw back commission"],
    bestFor: "TikTok creators, short-video influencers",
    approvalDifficulty: "easy",
    trackingReliability: 86,
  },
  {
    id: "ltk",
    name: "LTK (RewardStyle)",
    url: "https://ltk.app",
    signupUrl: "https://creators.shopltk.com",
    category: "fashion",
    commissionRate: "7–20%",
    cookieLength: "Varies",
    payoutType: "CPS",
    minPayout: "$100",
    payoutMethods: ["Bank transfer", "Check"],
    rating: 4.1,
    founded: 2011,
    merchants: 7000,
    regions: ["US", "UK", "AU", "BR", "DE", "FR", "KR"],
    pros: ["Premium fashion brands", "High-converting shoppable content", "Exclusive collaborations"],
    cons: ["Invite-only or requires strong following", "Fashion focus", "$100 minimum"],
    bestFor: "Fashion, beauty, lifestyle Instagram influencers",
    approvalDifficulty: "hard",
    trackingReliability: 90,
  },
];

export function scoreNetwork(n: AffiliateNetwork): number {
  let score = n.rating * 18;
  score += Math.min(15, n.trackingReliability / 7);
  score += n.cookieLength.includes("90") ? 8 : n.cookieLength.includes("60") ? 6 : n.cookieLength.includes("30") ? 4 : 1;
  if (n.payoutType === "RevShare" || n.payoutType === "Hybrid") score += 5;
  if (n.minPayout.startsWith("$1") || n.minPayout.startsWith("$5") || n.minPayout.startsWith("$10")) score += 5;
  if (n.approvalDifficulty === "easy") score += 5;
  else if (n.approvalDifficulty === "medium") score += 2;
  return Math.round(Math.min(100, score));
}
