import type { AffiliateOffer } from "./types";

// Real affiliate programs with publicly-known commission structures.
// Commission rates and EPC estimates are public data from each network.
export const AFFILIATE_OFFERS: AffiliateOffer[] = [
  // ===== SaaS / B2B (highest commissions, recurring) =====
  {
    id: "shopify",
    networkId: "impact",
    title: "Shopify — Start & grow your store",
    brand: "Shopify",
    description: "Leading e-commerce platform. Earn bounties when referrals start paid plans.",
    category: "SaaS / E-commerce",
    commission: "$150 per referral (bounty) or 20% recurring in some regions",
    commissionValue: 150,
    commissionType: "flat",
    epc: 58.0,
    conversionRate: 4.2,
    cookieLength: "30 days",
    payout: "$150 per paid referral",
    url: "https://www.shopify.com/affiliates",
    trending: "up",
    trendingPct: 22,
    gravity: 980,
    regions: ["Worldwide"],
    tags: ["recurring", "saaS", "high-ticket", "business"],
    influencerFit: 92,
    recurring: true,
    image: "🛍️",
  },
  {
    id: "canva",
    networkId: "impact",
    title: "Canva Pro — Design tool for everyone",
    brand: "Canva",
    description: "Freemium design tool with 175M+ users. Great conversion to Pro.",
    category: "SaaS / Design",
    commission: "Up to $26.70 per Canva Pro referral",
    commissionValue: 26.7,
    commissionType: "flat",
    epc: 3.4,
    conversionRate: 6.8,
    cookieLength: "30 days",
    payout: "$6.70–$26.70 per referral",
    url: "https://www.canva.com/affiliates/",
    trending: "up",
    trendingPct: 18,
    gravity: 1500,
    regions: ["Worldwide"],
    tags: ["design", "creators", "freemium", "easy-conversion"],
    influencerFit: 95,
    recurring: false,
    image: "🎨",
  },
  {
    id: "hubspot",
    networkId: "impact",
    title: "HubSpot — CRM & marketing suite",
    brand: "HubSpot",
    description: "Marketing, sales & CRM platform. Top-tier B2B commissions.",
    category: "SaaS / B2B",
    commission: "Up to $1,000+ per product purchase + recurring",
    commissionValue: 1000,
    commissionType: "flat",
    epc: 84.0,
    conversionRate: 1.8,
    cookieLength: "90 days",
    payout: "Up to $1,000 flat or 15% recurring",
    url: "https://www.hubspot.com/affiliates",
    trending: "stable",
    trendingPct: 4,
    gravity: 320,
    regions: ["Worldwide"],
    tags: ["b2b", "high-ticket", "recurring", "crm"],
    influencerFit: 70,
    recurring: true,
    image: "📊",
  },
  {
    id: "semrush",
    networkId: "partnerstack",
    title: "Semrush — SEO & marketing toolkit",
    brand: "Semrush",
    description: "All-in-one SEO, PPC & content platform. Strong for marketers.",
    category: "SaaS / Marketing",
    commission: "$0.01 per sign-up + $10 per trial + $130 per subscription",
    commissionValue: 130,
    commissionType: "flat",
    epc: 24.0,
    conversionRate: 3.1,
    cookieLength: "120 days",
    payout: "$200 per new sale, $10 per trial, $0.01 per signup",
    url: "https://www.semrush.com/affiliates/",
    trending: "up",
    trendingPct: 12,
    gravity: 650,
    regions: ["Worldwide"],
    tags: ["seo", "marketing", "recurring", "high-epc"],
    influencerFit: 78,
    recurring: true,
    image: "🔍",
  },
  {
    id: "convertkit",
    networkId: "partnerstack",
    title: "ConvertKit — Email marketing for creators",
    brand: "ConvertKit",
    description: "Creator-focused email marketing. Recurring 30% commission.",
    category: "SaaS / Creators",
    commission: "30% recurring commission",
    commissionValue: 30,
    commissionType: "percent",
    epc: 8.2,
    conversionRate: 3.8,
    cookieLength: "60 days",
    payout: "30% recurring monthly",
    url: "https://convertkit.com/affiliates",
    trending: "up",
    trendingPct: 15,
    gravity: 280,
    regions: ["Worldwide"],
    tags: ["creators", "email", "recurring", "saas"],
    influencerFit: 90,
    recurring: true,
    image: "✉️",
  },
  {
    id: "notion",
    networkId: "partnerstack",
    title: "Notion — Workspace & notes",
    brand: "Notion",
    description: "Productivity app with huge creator audience. 50% recurring for first year.",
    category: "SaaS / Productivity",
    commission: "50% of first year",
    commissionValue: 50,
    commissionType: "percent",
    epc: 6.5,
    conversionRate: 5.2,
    cookieLength: "90 days",
    payout: "50% first-year revenue",
    url: "https://www.notion.so/affiliates",
    trending: "up",
    trendingPct: 28,
    gravity: 540,
    regions: ["Worldwide"],
    tags: ["productivity", "creators", "recurring", "saas"],
    influencerFit: 88,
    recurring: true,
    image: "📝",
  },

  // ===== Finance =====
  {
    id: "wise",
    networkId: "impact",
    title: "Wise (TransferWise) — Global money transfers",
    brand: "Wise",
    description: "Cheap international transfers. Bounty for each new customer.",
    category: "Finance",
    commission: "£10 per invited friend who sends £200+",
    commissionValue: 12,
    commissionType: "flat",
    epc: 2.1,
    conversionRate: 9.5,
    cookieLength: "Session / referral link",
    payout: "$10–$70 per referral depending on country",
    url: "https://wise.com/invite",
    trending: "up",
    trendingPct: 19,
    gravity: 1200,
    regions: ["Worldwide"],
    tags: ["finance", "travel", "freelancers", "high-conversion"],
    influencerFit: 85,
    recurring: false,
    image: "💸",
  },
  {
    id: "revolut",
    networkId: "impact",
    title: "Revolut — Digital banking app",
    brand: "Revolut",
    description: "Popular banking and crypto app with generous referral bounties.",
    category: "Finance",
    commission: "$10–$30 per verified referral",
    commissionValue: 25,
    commissionType: "flat",
    epc: 4.5,
    conversionRate: 12.0,
    cookieLength: "Referral-specific",
    payout: "$10–$60 per referral (varies by country)",
    url: "https://www.revolut.com/referral/",
    trending: "up",
    trendingPct: 35,
    gravity: 980,
    regions: ["EU", "UK", "US", "AU"],
    tags: ["finance", "banking", "crypto", "high-conversion"],
    influencerFit: 82,
    recurring: false,
    image: "💳",
  },
  {
    id: "nordvpn",
    networkId: "impact",
    title: "NordVPN — VPN & online security",
    brand: "NordVPN",
    description: "One of the best-known VPNs. Strong commissions & creative assets.",
    category: "Software / Security",
    commission: "30–100% of new signup + 30% recurring renewal",
    commissionValue: 30,
    commissionType: "percent",
    epc: 42.0,
    conversionRate: 7.5,
    cookieLength: "30 days",
    payout: "Up to 100% on first month, 30% recurring",
    url: "https://nordvpn.com/affiliate/",
    trending: "up",
    trendingPct: 14,
    gravity: 850,
    regions: ["Worldwide"],
    tags: ["security", "privacy", "vpn", "recurring", "high-epc"],
    influencerFit: 80,
    recurring: true,
    image: "🔒",
  },

  // ===== Tech & gadgets =====
  {
    id: "logitech",
    networkId: "amazon-associates",
    title: "Logitech peripherals — Mice, keyboards, webcams",
    brand: "Logitech",
    description: "Popular tech accessories. Good for creators and remote workers.",
    category: "Tech / Electronics",
    commission: "Up to 4% via Amazon",
    commissionValue: 4,
    commissionType: "percent",
    epc: 0.8,
    conversionRate: 12.0,
    cookieLength: "24 hours",
    payout: "1–4% per sale (Amazon rates)",
    url: "https://www.logitech.com",
    trending: "stable",
    trendingPct: 2,
    gravity: 720,
    regions: ["Worldwide"],
    tags: ["tech", "creators", "gaming", "setup"],
    influencerFit: 72,
    recurring: false,
    image: "🖱️",
  },

  // ===== Fashion & beauty =====
  {
    id: "shein",
    networkId: "awin",
    title: "SHEIN — Fast fashion",
    brand: "SHEIN",
    description: "Massive fast-fashion brand. Huge conversion on TikTok/Instagram.",
    category: "Fashion",
    commission: "7–20% per sale",
    commissionValue: 15,
    commissionType: "percent",
    epc: 3.2,
    conversionRate: 5.8,
    cookieLength: "30 days",
    payout: "10–20% per sale, monthly bonuses",
    url: "https://us.shein.com/Affiliate-a-343.html",
    trending: "up",
    trendingPct: 24,
    gravity: 2100,
    regions: ["US", "UK", "EU", "Worldwide"],
    tags: ["fashion", "tiktok", "trending", "women"],
    influencerFit: 94,
    recurring: false,
    image: "👗",
  },
  {
    id: "gymshark",
    networkId: "impact",
    title: "Gymshark — Fitness apparel",
    brand: "Gymshark",
    description: "Fitness apparel brand. Strong with gym/fitness creators.",
    category: "Fitness / Fashion",
    commission: "8–10% per sale",
    commissionValue: 10,
    commissionType: "percent",
    epc: 4.8,
    conversionRate: 4.2,
    cookieLength: "30 days",
    payout: "10% commission",
    url: "https://www.gymshark.com/pages/affiliates",
    trending: "up",
    trendingPct: 11,
    gravity: 680,
    regions: ["US", "UK", "EU", "AU"],
    tags: ["fitness", "gym", "apparel", "lifestyle"],
    influencerFit: 86,
    recurring: false,
    image: "🏋️",
  },
  {
    id: "sephora",
    networkId: "rakuten",
    title: "Sephora — Beauty retailer",
    brand: "Sephora",
    description: "Premium beauty retailer with strong repeat-customer rate.",
    category: "Beauty",
    commission: "5–10% per sale",
    commissionValue: 7,
    commissionType: "percent",
    epc: 5.2,
    conversionRate: 8.0,
    cookieLength: "7 days",
    payout: "5% standard, 10% for approved influencers",
    url: "https://www.sephora.com/beauty/affiliate-program",
    trending: "stable",
    trendingPct: 3,
    gravity: 920,
    regions: ["US", "CA"],
    tags: ["beauty", "makeup", "skincare", "women"],
    influencerFit: 84,
    recurring: false,
    image: "💄",
  },
  {
    id: "glossier",
    networkId: "rakuten",
    title: "Glossier — DTC beauty",
    brand: "Glossier",
    description: "Cult beauty brand with strong social presence.",
    category: "Beauty",
    commission: "10% per sale",
    commissionValue: 10,
    commissionType: "percent",
    epc: 6.8,
    conversionRate: 5.5,
    cookieLength: "7 days",
    payout: "10% per sale",
    url: "https://www.glossier.com/affiliates",
    trending: "stable",
    trendingPct: 1,
    gravity: 410,
    regions: ["US", "UK", "CA"],
    tags: ["beauty", "skincare", "dtc", "aesthetic"],
    influencerFit: 80,
    recurring: false,
    image: "✨",
  },

  // ===== Health / supplements =====
  {
    id: "goli",
    networkId: "shareasale",
    title: "Goli Nutrition — Gummy vitamins",
    brand: "Goli",
    description: "Viral gummy supplement brand. High commission, generous creative.",
    category: "Health / Supplements",
    commission: "15% per sale + bonuses",
    commissionValue: 15,
    commissionType: "percent",
    epc: 12.0,
    conversionRate: 5.0,
    cookieLength: "30 days",
    payout: "15% commission, performance bonuses up to 20%",
    url: "https://goli.com/pages/affiliates",
    trending: "up",
    trendingPct: 9,
    gravity: 1100,
    regions: ["US", "UK", "EU", "AU"],
    tags: ["health", "supplements", "wellness", "high-commission"],
    influencerFit: 88,
    recurring: false,
    image: "🍎",
  },
  {
    id: "future",
    networkId: "impact",
    title: "Future — Personal coaching app",
    brand: "Future",
    description: "1-on-1 remote personal training. Recurring commissions.",
    category: "Fitness / Health",
    commission: "Up to $60 per signup + recurring",
    commissionValue: 60,
    commissionType: "flat",
    epc: 18.0,
    conversionRate: 3.2,
    cookieLength: "30 days",
    payout: "$60 per new customer",
    url: "https://www.future.co/affiliates",
    trending: "up",
    trendingPct: 16,
    gravity: 180,
    regions: ["US"],
    tags: ["fitness", "coaching", "recurring", "high-ticket"],
    influencerFit: 76,
    recurring: true,
    image: "🏃",
  },

  // ===== Education =====
  {
    id: "skillshare",
    networkId: "impact",
    title: "Skillshare — Online creative classes",
    brand: "Skillshare",
    description: "Online learning platform. Generous free-trial bounties.",
    category: "Education",
    commission: "$7 per free trial signup",
    commissionValue: 7,
    commissionType: "flat",
    epc: 1.8,
    conversionRate: 11.0,
    cookieLength: "30 days",
    payout: "$7 per new free trial",
    url: "https://www.skillshare.com/affiliates",
    trending: "up",
    trendingPct: 7,
    gravity: 580,
    regions: ["Worldwide"],
    tags: ["education", "creators", "free-trial", "easy"],
    influencerFit: 91,
    recurring: false,
    image: "🎓",
  },
  {
    id: "coursera",
    networkId: "impact",
    title: "Coursera — Online courses & degrees",
    brand: "Coursera",
    description: "University-level online courses. Bounty per signup.",
    category: "Education",
    commission: "Up to 45% on courses, 15% on subscriptions",
    commissionValue: 45,
    commissionType: "percent",
    epc: 5.4,
    conversionRate: 4.8,
    cookieLength: "30 days",
    payout: "15–45% per sale",
    url: "https://www.coursera.org/about/affiliates",
    trending: "stable",
    trendingPct: 2,
    gravity: 490,
    regions: ["Worldwide"],
    tags: ["education", "courses", "career", "professional"],
    influencerFit: 74,
    recurring: false,
    image: "📚",
  },

  // ===== Web hosting / developer tools =====
  {
    id: "siteground",
    networkId: "shareasale",
    title: "SiteGround — Web hosting",
    brand: "SiteGround",
    description: "Popular WordPress hosting with high bounties per referral.",
    category: "Web Hosting",
    commission: "$50–$125 per sale",
    commissionValue: 75,
    commissionType: "flat",
    epc: 22.0,
    conversionRate: 2.1,
    cookieLength: "60 days",
    payout: "$50–$125 per hosting signup",
    url: "https://www.siteground.com/affiliates",
    trending: "stable",
    trendingPct: 1,
    gravity: 420,
    regions: ["Worldwide"],
    tags: ["hosting", "wordpress", "high-ticket", "bounty"],
    influencerFit: 70,
    recurring: false,
    image: "🌐",
  },
  {
    id: "webflow",
    networkId: "impact",
    title: "Webflow — Visual website builder",
    brand: "Webflow",
    description: "No-code website builder popular with designers. Recurring commission.",
    category: "SaaS / Web",
    commission: "50% of first year",
    commissionValue: 50,
    commissionType: "percent",
    epc: 14.0,
    conversionRate: 3.4,
    cookieLength: "90 days",
    payout: "50% first-year revenue",
    url: "https://webflow.com/affiliates",
    trending: "up",
    trendingPct: 26,
    gravity: 310,
    regions: ["Worldwide"],
    tags: ["no-code", "web-design", "recurring", "saas"],
    influencerFit: 84,
    recurring: true,
    image: "🎯",
  },

  // ===== Home / lifestyle =====
  {
    id: "brooklinen",
    networkId: "shareasale",
    title: "Brooklinen — Luxury bedding",
    brand: "Brooklinen",
    description: "DTC bedding brand. Strong AOV and commission.",
    category: "Home",
    commission: "8% per sale",
    commissionValue: 8,
    commissionType: "percent",
    epc: 9.5,
    conversionRate: 3.5,
    cookieLength: "30 days",
    payout: "8% per sale",
    url: "https://www.brooklinen.com/pages/affiliate-program",
    trending: "up",
    trendingPct: 6,
    gravity: 160,
    regions: ["US", "CA"],
    tags: ["home", "lifestyle", "bedding", "high-aov"],
    influencerFit: 72,
    recurring: false,
    image: "🛏️",
  },
  {
    id: "hellofresh",
    networkId: "impact",
    title: "HelloFresh — Meal-kit delivery",
    brand: "HelloFresh",
    description: "Meal-kit subscription. High bounty per signup, food-recipe content fit.",
    category: "Food / Subscription",
    commission: "$10–$24 per signup",
    commissionValue: 18,
    commissionType: "flat",
    epc: 16.0,
    conversionRate: 4.0,
    cookieLength: "14 days",
    payout: "$10–$24 per new customer",
    url: "https://www.hellofresh.com/about/affiliate",
    trending: "up",
    trendingPct: 8,
    gravity: 640,
    regions: ["US", "UK", "DE", "CA", "AU"],
    tags: ["food", "subscription", "recipes", "family"],
    influencerFit: 86,
    recurring: false,
    image: "🥗",
  },

  // ===== Creator / tools =====
  {
    id: "epidemicsound",
    networkId: "impact",
    title: "Epidemic Sound — Royalty-free music",
    brand: "Epidemic Sound",
    description: "Music subscription for YouTubers/TikTokers. Perfect creator audience.",
    category: "SaaS / Creators",
    commission: "Up to $40 per subscription",
    commissionValue: 40,
    commissionType: "flat",
    epc: 12.0,
    conversionRate: 4.5,
    cookieLength: "30 days",
    payout: "$15–$40 per referral",
    url: "https://www.epidemicsound.com/affiliates/",
    trending: "up",
    trendingPct: 30,
    gravity: 380,
    regions: ["Worldwide"],
    tags: ["creators", "youtube", "music", "subscription"],
    influencerFit: 93,
    recurring: true,
    image: "🎵",
  },
  {
    id: "squarespace",
    networkId: "impact",
    title: "Squarespace — Website builder",
    brand: "Squarespace",
    description: "All-in-one website platform. Strong commissions and creative assets.",
    category: "SaaS / Web",
    commission: "$20–$62 per referral",
    commissionValue: 62,
    commissionType: "flat",
    epc: 14.0,
    conversionRate: 3.0,
    cookieLength: "45 days",
    payout: "$20–$62 per subscription",
    url: "https://www.squarespace.com/affiliates",
    trending: "stable",
    trendingPct: 2,
    gravity: 520,
    regions: ["Worldwide"],
    tags: ["website", "creators", "portfolio", "high-ticket"],
    influencerFit: 82,
    recurring: false,
    image: "🟦",
  },
  {
    id: "fiverr",
    networkId: "impact",
    title: "Fiverr — Freelance services marketplace",
    brand: "Fiverr",
    description: "Freelance marketplace. CPA up to $150 per first-time buyer.",
    category: "Freelance / Business",
    commission: "10–50% (up to $150 CPA)",
    commissionValue: 150,
    commissionType: "flat",
    epc: 9.5,
    conversionRate: 4.8,
    cookieLength: "30 days",
    payout: "$15–$150 per first-time buyer",
    url: "https://affiliates.fiverr.com",
    trending: "up",
    trendingPct: 12,
    gravity: 870,
    regions: ["Worldwide"],
    tags: ["freelance", "business", "cpa", "high-ticket"],
    influencerFit: 78,
    recurring: false,
    image: "🖥️",
  },
];
